import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { HeaderAndSideBar } from '@/app/HeaderAndSideBar';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <HeaderAndSideBar />

          <div className="p-4 sm:ml-64">
            <div className="mt-14">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
